version: '4.28.0'

networks:
  blog-cms-app:
    driver: bridge

volumes:
  dbdata:
    driver: local

services:
  app:
    build:
      args:
        user: blog-cms-app
        uid: 1000
      context: ./.docker/app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./.docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - blog-cms-app

  blog-cms-app-web:
    image: nginx
    container_name: blog-cms-app-web
    restart: unless-stopped
    ports:
      - "8002:80"
    networks:
      - blog-cms-app
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d

  blog-cms-app-db:
    networks:
      - blog-cms-app
    image: mysql:8.3.0
    container_name: blog-cms-app-db
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3307"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql


